/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rfid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Pratik
 */
public class bukupdate extends javax.swing.JFrame {

    /**
     * Creates new form bukupdate
     */
    public bukupdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 270, 231, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(381, 640, 120, 38);

        jLabel76.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(153, 255, 0));
        jLabel76.setText("Book Id :");
        getContentPane().add(jLabel76);
        jLabel76.setBounds(190, 270, 80, 20);

        jLabel17.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 0));
        jLabel17.setText("Author Name :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(170, 330, 130, 19);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(330, 330, 231, 30);

        jLabel16.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 0));
        jLabel16.setText("Book Name :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(170, 400, 110, 19);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17);
        jTextField17.setBounds(330, 390, 231, 30);

        jLabel65.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(153, 255, 0));
        jLabel65.setText("Author Mark :");
        getContentPane().add(jLabel65);
        jLabel65.setBounds(160, 450, 140, 19);

        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField44);
        jTextField44.setBounds(330, 450, 231, 30);

        jLabel18.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 0));
        jLabel18.setText("Publishing Year :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(660, 450, 150, 19);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(830, 450, 231, 30);

        jLabel62.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(153, 255, 0));
        jLabel62.setText("No. Of Copies :");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(170, 500, 130, 30);
        getContentPane().add(jTextField43);
        jTextField43.setBounds(330, 510, 231, 30);

        jLabel63.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(153, 255, 0));
        jLabel63.setText("Date :");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(190, 570, 70, 19);

        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField42);
        jTextField42.setBounds(330, 570, 231, 30);

        jLabel61.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(153, 255, 0));
        jLabel61.setText("ISBN Number :");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(680, 330, 126, 19);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(830, 330, 231, 30);

        jLabel64.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(153, 255, 0));
        jLabel64.setText("Language CD :");
        getContentPane().add(jLabel64);
        jLabel64.setBounds(670, 390, 130, 30);

        jLabel66.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(153, 255, 0));
        jLabel66.setText("Bibliography :");
        getContentPane().add(jLabel66);
        jLabel66.setBounds(670, 510, 123, 19);

        jScrollPane7.setMinimumSize(new java.awt.Dimension(32767, 32767));

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(830, 510, 230, 57);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(830, 390, 231, 30);

        jLabel15.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 255));
        jLabel15.setText("       Book Update");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(400, 154, 510, 60);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(579, 640, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bookupdt.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1340, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
            Connection con;
            con=DriverManager.getConnection("jdbc:odbc:rfid","sa","123456");
            System.out.println("Connection to the database is done.");
           /*String stdt=  jTextField2.getText();
            String fnm=jTextField3.getText();
                    if(fnm.matches( "'{5,25}' placeholder='name with alphabets & space only' required=\"required\""))
                     {
                         System.out.println("Successfully");
                     }
                     else
                     {
                         System.out.println("UNSuccessfully");
                     }
              //pattern='{5,25}'placeholder='name with alphabets & space only' required="required"/>
            //String fnm=  jTextField3.getText();*/
            String bkid=jTextField1.getText();
          String ca= jTextField16.getText();
          String ct=jTextField17.getText();
          String am=jTextField44.getText();
          String cp=jTextField43.getText();
         String py=jTextField18.getText();
                 String lcd=jTextField6.getText();
                 String cty="M";
                         //jTextField5.getText();
                 String isbn=jTextField4.getText();
                 String adt=jTextField42.getText();
                 String bg=jTextArea1.getText();
           Statement s=con.createStatement();
                 
         s.executeUpdate("UPDATE Card SET CardAuthor='"+ca+"',CardTitle='"+ct+"',CardType='"+cty+"',Copies='"+cp+"',AuthorMark='"+am+"',PublicationYear='"+py+"',LanguageCD='"+lcd+"',ISBNNumber='"+isbn+"',AddDT='"+adt+"',Bibliography='"+bg+"' WHERE CatRefNum='"+bkid+"'");
            
         //  PreparedStatement s=con.prepareStatement("UPDATE Card SET CardAuthor='"+jTextField48.getText()+"',CardTitle='"+jTextField49.getText()+"',AuthorMark='"+jTextField54.getText()+"',CardType='"+jTextField55+"',PublicationYear='"+jTextField50.getText()+"',LanguageCD='"+jTextField56.getText()+"',Copies='"+jTextField52.getText()+"',ISBNNumber='"+jTextField53.getText()+"',AddDT='"+jTextField51.getText()+"',Bibliography='"+jTextArea2.getText()+"' WHERE CatRefNum='"+bkid+"'");
           System.out.print(""+s);
            //Statement s=con.prepareStatement(s);
            //s.executeUpdate();
            
            //s.executeUpdate("INSERT INTO Borrowers(BorrowerID,FirstName,LastName,Address,Salutation,OrganizationName,DepartmentName,City,State,PostalCode,Country,ContactName,ContactTitle,PhoneNumber,Extension,FaxNumber,EmailName,Note,CategoryID,MemBegDate,MemEndDate,Priority,CurrentDues,Deposit,ReceiptNo,ReceiptDate,Password,FeesDue,FinesDue,OperatorID,Address2,City2,State2,PostalCode2,SupervisorID2,Country2,SIP2Blocked,SIP2BlockedMessage,SIP2CardRetained,ServiceLine,IndustryLine,Activated,WorkPlace,BorrBarcodeNum,trpBorrID,BirthDate,BloodGroup,revUserID,MobileNumber) VALUES('"+browid+"','"+fnm+"','"+lnm+"','"+adress+"','"+stdnm+"','""','"brnch"','""','""','""','"+pcod+"','""','""','"+phno+"','""','""','"+eid+"','""','"+yr+"','"+dat+"','"+memenddt+"',9, 0,0,'""',null,'MEMBER',0,0,'"+curuser+"','""','""','""','""','""','""','N','""','N','""','""',1,'Main','"+browid+"','""',null,'""','"+curuser+"','"+mobno+"')");
         //s.executeUpdate("INSERT INTO Borrowers(BorrowerID,FirstName,LastName,Address,Salutation,OrganizationName,DepartmentName,City,State,PostalCode,Country,ContactName,ContactTitle,PhoneNumber,Extension,FaxNumber,EmailName,Note,CategoryID,MemBegDate,MemEndDate,Priority,CurrentDues,Deposit,ReceiptNo,ReceiptDate,Password,FeesDue,FinesDue,OperatorID,Address2,City2,State2,PostalCode2,SupervisorID2,Country2,SIP2Blocked,SIP2BlockedMessage,SIP2CardRetained,ServiceLine,IndustryLine,Activated,WorkPlace,BorrBarcodeNum,trpBorrID,BirthDate,BloodGroup,revUserID,MobileNumber) VALUES('"+browid+"','"+fnm+"','"+lnm+"','"+adress+"','"+stdnm+"','','"+brnch+"','"+city+"','','"+pcod+"','','','','"+phno+"','','','"+eid+"','','"+yr+"','"+dat+"','"+memenddt+"',9, 0,0,'',null,'MEMBER',0,0,'"+curuser+"','','','','','','','N','','N','','',00000001,'Main','"+browid+"','',null,'','"+curuser+"','"+mobno+"')");
         JOptionPane.showMessageDialog(null,"Book is Updated Successfully..");
       
        }
        catch(SQLException se)
        {
            System.out.print(se);
            JOptionPane.showMessageDialog(null,"Oops...Something goes Wrong..please Check" );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         jTextField1.setText("");
          jTextField16.setText("");
          jTextField17.setText("");
          jTextField44.setText("");
          jTextField43.setText("");
         jTextField18.setText("");
         jTextField6.setText("");
       //  jTextField5.setText("");
         jTextField4.setText("");
        jTextField42.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bukupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bukupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bukupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bukupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bukupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JScrollPane jScrollPane7;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField16;
    public static javax.swing.JTextField jTextField17;
    public static javax.swing.JTextField jTextField18;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField42;
    public static javax.swing.JTextField jTextField43;
    public static javax.swing.JTextField jTextField44;
    public static javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
