/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rfid;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Mantesh
 */
public class loandays extends javax.swing.JFrame {

    /**
     * Creates new form loandays
     */
    Connection con;
    public loandays() {
        initComponents();
        try{
            
            con=DriverManager.getConnection("jdbc:odbc:rfid","sa","123456");
            System.out.println("Connection to the database is done.");
            
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "FE", "SE", "TE", "BE", "IN", "POL", "NTS", "HOD", "PG" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("LoanDays :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Book Circulation Rules");

        jLabel3.setText("Fine Rate :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Statement s=con.createStatement();
             ResultSet rs1=null;
             int ld;
             String lnm="";
            
            
            /*
            if(1==jComboBox1.getSelectedIndex())
            {
                lnm="FE";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(2==jComboBox1.getSelectedIndex())
            {
                lnm="SE";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(3==jComboBox1.getSelectedIndex())
            {
                lnm="TE";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(4==jComboBox1.getSelectedIndex())
            {
                lnm="BE";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(5==jComboBox1.getSelectedIndex())
            {
                lnm="IN";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(6==jComboBox1.getSelectedIndex())
            {
                lnm="POL";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            if(7==jComboBox1.getSelectedIndex())
            {
                lnm="NTS";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }if(8==jComboBox1.getSelectedIndex())
            {
                lnm="HOD";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }if(9==jComboBox1.getSelectedIndex())
            {
                lnm="PG";
                 rs1 =s.executeQuery("Select min(LoanDays) as ldays from CircRules where categoryid='"+lnm+"'");
            
            }
            */
             
            rs1=s.executeQuery("select loandays,finerate from circrules where categoryid='"+jComboBox1.getSelectedItem()+"' order by loandays");
            System.out.println(jComboBox1.getSelectedItem());
            while(rs1.next())
            {
                ld=rs1.getInt("loandays");
                 jTextField1.setText(Integer.toString(ld));
                 jTextField2.setText(rs1.getString("finerate"));
             }
            
           
                 rs1.close();
            s.close();
            
        }
        catch(SQLException e)
        {
            
            System.out.println("...."+e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    try
        {

            Statement s=con.createStatement();
            // ResultSet rs1=null;
             
             int lf1;
             //lds=Integer.parseInt(jTextField1.getText());
             lf1=Integer.parseInt(jTextField1.getText());
             System.out.println(lf1);
            // int i=jComboBox1.getSelectedIndex();
             String tlds="";
   
            
            if(1==jComboBox1.getSelectedIndex())
            {
                tlds="FE";
                 s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
                
            }
           if(2==jComboBox1.getSelectedIndex())
            {
                tlds="SE";
                 s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }
            if(3==jComboBox1.getSelectedIndex())
            {
                tlds="TE";
                 s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }
            if(4==jComboBox1.getSelectedIndex())
            {
                tlds="BE";
                s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }
            if(5==jComboBox1.getSelectedIndex())
            {
                tlds="IN";
                 s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            }
            if(6==jComboBox1.getSelectedIndex())
            {
                tlds="POL";
               s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }
            if(7==jComboBox1.getSelectedIndex())
            {
                tlds="NTS";
               s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }if(8==jComboBox1.getSelectedIndex())
            {
                tlds="HOD";
                 s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }if(9==jComboBox1.getSelectedIndex())
            {
                tlds="PG";
                  s.executeUpdate("update circrules set LoanDays='"+lf1+"' where CategoryID='"+tlds+"'");
            
            }
             JOptionPane.showMessageDialog(null,"LoanDays Updated Sucessfully...!!!");
           
           // rs1.close();
            s.close();
            
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        loandays ld=new loandays();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loandays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loandays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loandays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loandays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loandays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
