/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Sep 24, 2014, 9:22:02 AM
 */
package rfid;

import java.awt.Toolkit;
import java.lang.*;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.applet.resources.MsgAppletViewer;
import sun.security.util.Password;
import jaco.mp3.player.MP3Player;
/**
 *
 * @author Pravin
 */
public class login extends javax.swing.JFrame {
Connection con;
    /** Creates new form login */
    public login() {
        initComponents();
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        }
   
        catch(ClassNotFoundException ce)
        {
            System.out.println("driver is loaded");
        }
        try
        {
            
            con=DriverManager.getConnection("jdbc:odbc:rfid","sa","123456");
            System.out.println("Connection to the database is done.");
        }
catch(SQLException ex)
        {
            System.out.print(ex);
        }
    }
    
    public void close(){

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
//chng frmae desault close oprtion to dispose
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log IN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(500, 375));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("Welcome to RFID Based");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 295, 31);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Username  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 110, 26);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Password : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 110, 26);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 140, 241, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 255));
        jButton1.setText("Log In ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 250, 95, 27);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 250, 93, 27);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 0));
        jLabel5.setText("Library Management System");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 70, 410, 25);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 190, 241, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/login1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -60, 490, 430);

        jLabel4.setText("Please Log In");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 310, 490, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String unm,pass;
            unm=jTextField1.getText();
             pass=jPasswordField1.getText();
            
            if(unm.isEmpty()||pass.isEmpty())
               jLabel4.setText("<HTML><FONT COLOR = red>*You must enter a USERNAME and PASSWORD to Login</FONT></HTML>");
            else{
              
                // mainpg m=new mainpg();
                 Connection conn = null;
            PreparedStatement s = null;
        try{  
            //Statement s=con.createStatement();
           // ResultSet rs=s.executeQuery("select * from tbloperators where opname='"+unm+"' and password='"+pass+"'");
            s =con.prepareStatement("SELECT * FROM tbloperators WHERE opname = ? AND password=?");
      //s.setString(1, unm);
            
         s.setString(1, unm);
         s.setString(2, pass);
         ResultSet rs= s.executeQuery();
            if(rs.next())   
            {
               
              //new mainpg().setVisible(true);

              new MP3Player(new File("src\\imgs\\rfid_welcome.mp3")).play();
                mainpg m= new mainpg();
                m.jTextField14.setText(unm.toUpperCase());   //passing username to mainpg
                m.jTextField35.setText(unm.toUpperCase());
                close();
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password");
            }
        }
        catch(SQLException ex)
        {
            System.out.print(ex);
        }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
