/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rfid;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;

/**
 *
 * @author Pratik
 */
public class stdupdate extends javax.swing.JFrame {

    /**
     * Creates new form stdupdate
     */
    public stdupdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText(" Borrower Details ...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 51, 580, 50);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 220, 120, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 220, 130, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(580, 150, 148, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(360, 210, 180, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 270, 90, 19);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("City :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 270, 80, 19);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Branch :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 320, 90, 20);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Year :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(720, 320, 94, 19);

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Email :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 380, 68, 19);

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Mobile Number :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 380, 150, 19);

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("PIN code :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 430, 90, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(810, 210, 170, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(810, 260, 170, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 260, 180, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(810, 380, 170, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(360, 380, 180, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 510, 130, 32);

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Student ID :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 160, 120, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(360, 430, 180, 30);

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Phone Number :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(640, 430, 140, 19);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(810, 430, 170, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 510, 100, 32);

        jComboBox1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(810, 320, 170, 30);

        jComboBox2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(360, 320, 180, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/stdupdate.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1830, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con;
            con=DriverManager.getConnection("jdbc:odbc:rfid","sa","123456");
            System.out.println("Connection to the database is done.");
            String stdid=jTextField1.getText();
             String fnm=jTextField2.getText();
                    
              
            
            
             String lnm=  jTextField3.getText();
             String stdnm=lnm+" "+fnm;
             String add=  jTextField5.getText();
             String city=  jTextField4.getText();
             String brch=(String)jComboBox2.getSelectedItem();
            String year=(String)jComboBox1.getSelectedItem();
             
             //String brch=  jTextField7.getText();
            // String year=  jTextField6.getText();
             String email=  jTextField9.getText();           
             String mobile=  jTextField8.getText();            
             String pin=  jTextField10.getText();
             String phn=  jTextField11.getText();
            
//             PreparedStatement s=con.prepareStatement("UPDATE Borrowers SET FirstName='"+fnm+"',LastName='"+lnm+"',Address='"+add+"',Salutation='"+stdnm+"',DepartmentName='"+brch+"',City='"+city+"',EmailName='"+email+"',CategoryID='"+year+"',MobileNumber='"+mobile+"' WHERE BorrowerID='"+stdt+"'");
             
         Statement s=con.createStatement();
                 s.executeUpdate("UPDATE Borrowers SET FirstName='"+fnm+"',LastName='"+lnm+"',Address='"+add+"',Salutation='"+stdnm+"',DepartmentName='"+brch+"',City='"+city+"',PostalCode='"+pin+"',PhoneNumber='"+phn+"',EmailName='"+email+"',CategoryID='"+year+"',MobileNumber='"+mobile+"' WHERE BorrowerID='"+stdid+"'");
          //PreparedStatement s=con.prepareStatement("UPDATE Borrowers SET FirstName='"+fnm+"',LastName='"+lnm+"',Address='"+add+"',Salutation='"+stdnm+"',DepartmentName='"+brch+"',City='"+city+"',PostalCode='"+pin+"',PhoneNumber='"+phno+"',EmailName='"+email+"',CategoryID='"+year+"',MobileNumber='"+mobile+"' WHERE BorrowerID='"+stdt+"'");
           //System.out.print("" +s);
          
            //s.executeUpdate();
            
          
         JOptionPane.showMessageDialog(null,"Student Updated Successfully..");
         
       
        }
        catch(SQLException se)
        {
            System.out.print(se);
            JOptionPane.showMessageDialog(null,"Oops... Duplicate Borrower ID is not Allowd" );
        }
                
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //new stdupdate().setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stdupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stdupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stdupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stdupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stdupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
